version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/register
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'